### PR TITLE
add an alternative sorting method

### PR DESCRIPTION
**Pull request by wodny**
Alternative sorting method via click + shift/alt and the data-sort-alt attribute.

## Purpose

I found a use case where a column has a numerical `data-sort` but sometimes it would be useful to sort just by the bool value of that numerical value.

## Approach

Added the `data-sort-alt` attribute with automatic fallback to `data-sort`.

## Fixes

The PR itself.

### CODE REVIEW

**Comment by tofsjonas** [comment]
I like it. But do we really need to pass `alt_sort` to getValue as a parameter? It's already available in the "global" scope...

**Comment by wodny** [comment]
I prefer passing parameters explicitly. I can see that eg. `regex_dir` is used implicitly but it works more like a constant here. Nevertheless, if you prefer non-explicit closure version I will change it. It's your code so I won't try to force any conventions. Shall I push another version?

**Comment by tofsjonas** [comment]
Yes, push it!

(To me `alt_sort` is also a form of constant, so it would fit in better with the existing code style)

**Comment by wodny** [comment]
> Yes, push it!

Done.

**Review by tofsjonas — APPROVED** [review]
Cool

**Pull request merged**
